name: CI Pipeline
on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'website/*'
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'website/*'
env:
  GO_VERSION: 1.17
jobs:
  compile:
    name: Compiliation
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: magnetikonline/action-golang-cache@v1
      with:
        go-version: ${{env.GO_VERSION}}
    - name: Go fmt
      run: |
        # exit 1 if any files need go fmt
        test -z $(gofmt -s -l .)

    - name: Go vet
      run: |
        go vet ./...

    - name: Go Build
      run: |
        go build -v .
  test:
    name: Testing
    needs: compile
    runs-on: ubuntu-20.04
    timeout-minutes: 16
    steps:
    - uses: actions/checkout@v2
    - uses: magnetikonline/action-golang-cache@v1
      with:
        go-version: ${{env.GO_VERSION}}
    - name: Unit tests
      timeout-minutes: 5
      run: |
        go test -v -race ./...
    - name: E2E tests
      timeout-minutes: 15
      env:
        E2E_TESTING: 1
      run: |
        go test -race -timeout=15m -v ./...
